version: "3"

services:
  php:
    image: php:7-apache
    volumes:
      # Montamos nuestra web desde fuera en el directorio web del contenedor
      - ./:/var/www/html
    expose:
      - 80
    ports:
      - 8080:80
